name: ed25519
description: Fast and efficient ed25519 signing and verification in pure Dart.
version: 0.0.1
homepage: https://github.com/DartCrypto/ed25519
author: Sun <huachuang20@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
